import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { Header } from "@/components/globals/header";
import { Toaster } from "sonner";

import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <Toaster />
      <NextTopLoader />
        <Header />

          <div className="container mx-auto">{children}</div>
      </Providers>
      </body>
    </html>
  );
}
